### ISSUE TITLE
Doc string contains non-ASCII character causing error during import when using PYTHONOPTIMIZE=1

### ISSUE THREAD

**Issue by sabgit** [MicroStrategy/mstrio-py#7]
It is all good like following:
```
$ python
>>> from mstrio import microstrategy
>>> 
```

But hitting this error like following:

```
$ export PYTHONOPTIMIZE=1
$ python
>>> from mstrio import microstrategy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/ub18/build/pyenv/local/lib/python2.7/site-packages/mstrio/microstrategy.py", line 9, in <module>
    from mstrio.api import projects, cubes, reports, authentication, datasets
  File "/tmp/ub18/build/pyenv/local/lib/python2.7/site-packages/mstrio/api/authentication.py", line 6
SyntaxError: Non-ASCII character '\xe2' in file /tmp/ub18/build/pyenv/local/lib/python2.7/site-packages/mstrio/api/authentication.py on line 7, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
>>> 
```

**Comment by scottrigney** [comment]
Closed in #16
